import { z } from "zod";

export const reportSchema = z.object({
  kind: z.enum([
    "summary",
    "revenue",
    "invoice-status",
    "paid",
    "outstanding",
    "overdue",
    "customer-balances",
    "payments",
    "expenses",
    "tax",
  ]),
  preset: z.enum([
    "today",
    "this_week",
    "this_month",
    "last_month",
    "this_quarter",
    "this_year",
    "custom",
  ]),
  dateFrom: z.string(),
  dateTo: z.string(),
  role: z.enum(["SUPER_ADMIN", "ADMIN", "MEMBER"]),
  scope: z.enum(["SYSTEM", "ORGANIZATION", "MEMBER", "ADMIN"]),
  organizationId: z.string().nullable(),
  memberId: z.string().nullable().optional(),
  currency: z.string(),
  overview: z.object({
    revenue: z.string(),
    taxCollected: z.string(),
    expenses: z.string(),
    payments: z.string(),
    invoices: z.number(),
    paidInvoices: z.number(),
    outstandingBalance: z.string(),
    overdueInvoices: z.number(),
  }),
  metrics: z.record(z.string(), z.union([z.string(), z.number()])),
  series: z.array(z.object({ label: z.string(), value: z.string() })),
  breakdown: z.array(z.object({ label: z.string(), value: z.string() })),
  table: z.object({
    columns: z.array(z.object({ key: z.string(), label: z.string() })),
    rows: z.array(z.record(z.string(), z.string())),
    page: z.number(),
    pageSize: z.number(),
    total: z.number(),
  }),
  organizations: z.array(z.object({ id: z.string(), name: z.string() })),
});
